name: SQL Linter
on:
  push:
    branches: [master]
jobs:
  SQLLinter:
    # використання Docker-imаgе із вказаною версією ОС
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: "actions/checkout@v3"
      - name: Start SQL Linter
        run: |
          pip install sqlfluff
          sqlfluff lint $GITHUB_WORKSPACE/query.sql --dialect postgres
