name: Print Software Versions

on:
  push:
    branches: [ master ]


jobs:
  # Перша робота для перевірки версій програмного забезпечення на рівні обробки даних
  print-processing-software-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show Python version
        run: php -v


  # Друга робота для перевірки версій СКБД на рівні доступу до даних
  print-database-software-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show PostgreSQL version
        run: psql --version
